controller_manager:
  ros__parameters:
    update_rate: 30 # Hz

    diff_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_controller:
  ros__parameters:
    
    odom_frame_id: odom
    base_frame_id: base_link

    position_feedback: false
    cmd_vel_timeout: 0.6

    linear.x.min_velocity: -0.15
    linear.x.max_velocity: 0.15

    angular.z.max_velocity: 0.5
    angular.z.min_velocity: -0.5

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.158
    wheel_radius: 0.033
