twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: cmd_vel
        timeout: 0.5
        priority: 10
      keyboard: 
        topic: diff_controller/cmd_vel
        timeout: 0.5
        priority: 100 